Update login example for Express 4
gurugray/passport-yandex pull request #3
Opened 2017-10-30 20:26 UTC by DarkScorpion

Update code and dependencies.

2017-10-31 08:36 UTC, gurugray commented
Спасибо за PR! давно не обновлял код :)

2017-10-31 08:45 UTC, gurugray requested changes

2017-10-31 08:45 UTC, gurugray commented on examples/login/app.js
> +var YANDEX_CALLBACK_URL = 'http://localhost:8080/auth/yandex/callback';
это не `YANDEX_CALLBACK`
если уж и оптимизировать тут, то стоит обозвать это как-то так:

```js
var LOCAL_CALLBACK_URL = '/auth/yandex/callback';

//…

app.get(LOCAL_CALLBACK_URL,…)

//…

passport.use(new YandexStrategy({
      clientID: YANDEX_CLIENT_ID,,
      clientSecret: YANDEX_CLIENT_SECRET,
      callbackURL: s1.address().host + s1.address().port + LOCAL_CALLBACK_URL
    },

//…
```

2017-10-31 17:10 UTC, DarkScorpion commented on examples/login/app.js
> +var YANDEX_CALLBACK_URL = 'http://localhost:8080/auth/yandex/callback';
callbackURL: s1.address().host + s1.address().port + LOCAL_CALLBACK_URL
Ошибка, s1 = undefined. Потому, что s1 объявляется ниже.

2017-10-31 17:15 UTC, DarkScorpion commented on examples/login/app.js
> +var YANDEX_CALLBACK_URL = 'http://localhost:8080/auth/yandex/callback';
> это не YANDEX_CALLBACK
> если уж и оптимизировать тут, то стоит обозвать это как-то так:

Тогда уж OAUTH2_CALLBACK_URL, потому что локальных калбеков может быть много.

2017-11-01 10:27 UTC, gurugray commented on examples/login/app.js
> +var YANDEX_CALLBACK_URL = 'http://localhost:8080/auth/yandex/callback';
>Ошибка, s1 = undefined. Потому, что s1 объявляется ниже.

ага, я имел ввиду использовать переменные окружения или настройки, чтобы не копипастить

2017-11-01 10:28 UTC, gurugray commented on examples/login/app.js
> +var YANDEX_CALLBACK_URL = 'http://localhost:8080/auth/yandex/callback';
>Тогда уж OAUTH2_CALLBACK_URL

согласен :)

2017-11-09 14:47 UTC, gurugray commented
добьёшь? :)

2026-09-16 22:15 UTC, closed without merging